userofficeproject/stfc-user-office-project#142-testing new command, commented old commands purely for testing

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -4,7 +4,7 @@ name: Build && Push
 # events but only for the develop branch
 on:
   push:
-    branches: [develop, master]
+    branches: [develop, master, 142_Trigger_Deployment_Factory]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -41,29 +41,33 @@ jobs:
       - name: Extracted branch
         run: echo "Extracted branch ${{ steps.extract_branch.outputs.branch }}"
 
-      - name: Build and push
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
-          build-args: BUILD_VERSION=${{ github.sha }}
-          push: true
-          tags: dmsc/duo-factory:${{ steps.extract_branch.outputs.branch }}
+      # - name: Build and push
+      #   id: docker_build
+      #   uses: docker/build-push-action@v2
+      #   with:
+      #     build-args: BUILD_VERSION=${{ github.sha }}
+      #     push: true
+      #     tags: dmsc/duo-factory:${{ steps.extract_branch.outputs.branch }}
 
-      - name: Trigger pipeline
-        run: |
-          REPOSITORY=${{ github.repository }}
-          RESULT=$(curl -X POST \
-            -F token="${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
-            -F ref=master \
-            -F "variables[RUN_DEPLOY]=1" \
-            -F "variables[BRANCH]=${{ steps.extract_branch.outputs.branch }}" \
-            -F "variables[REPOSITORY]=${REPOSITORY#UserOfficeProject/}" \
-            -o /dev/null \
-            --silent \
-            --write-out '%{http_code}' \
-            ${{ secrets.GITLAB_TRIGGER_URL }})
+      # - name: Trigger pipeline
+      #   run: |
+      #     REPOSITORY=${{ github.repository }}
+      #     RESULT=$(curl -X POST \
+      #       -F token="${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
+      #       -F ref=master \
+      #       -F "variables[RUN_DEPLOY]=1" \
+      #       -F "variables[BRANCH]=${{ steps.extract_branch.outputs.branch }}" \
+      #       -F "variables[REPOSITORY]=${REPOSITORY#UserOfficeProject/}" \
+      #       -o /dev/null \
+      #       --silent \
+      #       --write-out '%{http_code}' \
+      #       ${{ secrets.GITLAB_TRIGGER_URL }})
 
-          if [[ $RESULT != "201" ]]; then
-            echo "Failed to trigger Gitlab pipeline: $RESULT"
-            exit 1
-          fi
+      #     if [[ $RESULT != "201" ]]; then
+      #       echo "Failed to trigger Gitlab pipeline: $RESULT"
+      #       exit 1
+      #     fi
+
+      - name: Trigger Jenkins
+        run: | 
+          curl -k -l -u ${{ secrets.STFC_CI_TRIGGER_USERNAME }}:${{ secrets.STFC_CI_TRIGGER_TOKEN }} "${{ secrets.STFC_CI_TRIGGER_BASE_URL }}/Dev_Deploy_ProposalFactory.LatestImage/build?token=${{ secrets.STFC_CI_TRIGGER_URL_TOKEN }}"
